webtalk_init -webtalk_dir D:/Personali Gianlorenzo/Documenti/GitHub/Snake/snake.sim/sim_1/behav/xsim/xsim.dir/testgenerale_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 23 21:16:11 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c14bde19-9ae8-4980-bf05-31b72a09531f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a72e3c3731a54cbc9562f032f7dc352d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3492 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.65_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8584_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1023473764 -regid "" -xml D:/Personali Gianlorenzo/Documenti/GitHub/Snake/snake.sim/sim_1/behav/xsim/xsim.dir/testgenerale_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Personali Gianlorenzo/Documenti/GitHub/Snake/snake.sim/sim_1/behav/xsim/xsim.dir/testgenerale_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Personali Gianlorenzo/Documenti/GitHub/Snake/snake.sim/sim_1/behav/xsim/xsim.dir/testgenerale_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
